### ISSUE TITLE
Logo Proposal for single service queue simulation

### ISSUE THREAD

**Issue by candyskull920** [energy-in-joles/Single-Service-Queue-Simulation#1]
Hi @energy-in-joles 
I am an open source enthusiast and I am looking to expand my work portfolio.
I would like to collaborate with your project for free, I can provide you with a logo for your project

Good day
Skull C.

**Comment by energy-in-joles** [comment]
Hi @candyskull920 , unfortunately I don't intend to develop this project any further and hence will not be requiring a logo. Thanks so much for the offer though, wishing you all the best on your other projects!
